import {Game} from '../shared/types'

export const games: Game[] = [
    {
        id: 1,
        version: 2.0,
        title: "Dark Souls",
        description: "An action RPG set in a dark, medieval fantasy world filled with challenging enemies and intricate lore.",
        rating: 9.5,
        genre: "RPG",
        developer: "FromSoftware",
        adult: true,
    },
    {
        id: 1,
        version: 3.0,
        title: "Dark Souls II",
        description: "The second entry in the Dark Souls series, featuring enhanced mechanics and new locations.",
        rating: 8.9,
        genre: "RPG",
        developer: "FromSoftware",
        adult: true,
    },
    {
        id: 1,
        version: 1.0,
        title: "Dark Souls III",
        description: "The final entry in the Dark Souls trilogy, known for its challenging gameplay and rich lore.",
        rating: 9.3,
        genre: "RPG",
        developer: "FromSoftware",
        adult: true,
    },
    {
        id: 2,
        version: 1.0,
        title: "Gears of War",
        description: "A third-person shooter where players fight against a horde of alien creatures known as the Locust.",
        rating: 9.0,
        genre: "Shooter",
        developer: "Epic Games",
        adult: true,
    },
    {
        id: 2,
        version: 2.0,
        title: "Gears of War 2",
        description: "The sequel to Gears of War, featuring improved gameplay and a deeper storyline in the fight against the Locust.",
        rating: 9.1,
        genre: "Shooter",
        developer: "Epic Games",
        adult: true,
    },
    {
        id: 2,
        version: 3.0,
        title: "Gears of War 3",
        description: "The conclusion to the Gears of War trilogy, with an epic finale to the battle against the Locust and the Lambent.",
        rating: 9.2,
        genre: "Shooter",
        developer: "Epic Games",
        adult: true,
    },
];
